[2025-03-28T14:01:18.931+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-28T14:01:18.955+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superstore_dag.load_data_to_prod_db manual__2025-03-28T14:00:55.842262+00:00 [queued]>
[2025-03-28T14:01:18.969+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superstore_dag.load_data_to_prod_db manual__2025-03-28T14:00:55.842262+00:00 [queued]>
[2025-03-28T14:01:18.971+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-03-28T14:01:19.027+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_data_to_prod_db> on 2025-03-28 14:00:55.842262+00:00
[2025-03-28T14:01:19.035+0000] {standard_task_runner.py:72} INFO - Started process 679 to run task
[2025-03-28T14:01:19.041+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'superstore_dag', 'load_data_to_prod_db', 'manual__2025-03-28T14:00:55.842262+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/superstore_dag.py', '--cfg-path', '/tmp/tmpkc2es604']
[2025-03-28T14:01:19.044+0000] {standard_task_runner.py:105} INFO - Job 73: Subtask load_data_to_prod_db
[2025-03-28T14:01:19.119+0000] {task_command.py:467} INFO - Running <TaskInstance: superstore_dag.load_data_to_prod_db manual__2025-03-28T14:00:55.842262+00:00 [running]> on host b7fc87b83960
[2025-03-28T14:01:19.333+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='superstore_dag' AIRFLOW_CTX_TASK_ID='load_data_to_prod_db' AIRFLOW_CTX_EXECUTION_DATE='2025-03-28T14:00:55.842262+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-28T14:00:55.842262+00:00'
[2025-03-28T14:01:19.336+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-28T14:01:19.337+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-28T14:01:19.339+0000] {logging_mixin.py:190} INFO - Current task name:load_data_to_prod_db state:running start_date:2025-03-28 14:01:18.957149+00:00
[2025-03-28T14:01:19.340+0000] {logging_mixin.py:190} INFO - Dag name:superstore_dag and current dag run status:running
[2025-03-28T14:01:19.342+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-28T14:01:19.357+0000] {logging_mixin.py:190} INFO - Checking and potentially creating table: prod_fact_table
[2025-03-28T14:01:19.369+0000] {base.py:84} INFO - Retrieving connection '***_default'
[2025-03-28T14:01:19.396+0000] {sql.py:624} INFO - Running statement: 
            IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'prod_fact_table')
            BEGIN
                CREATE TABLE prod_fact_table ([OrderID_SK] INT, [ProductID_SK] INT, [CustomerID_SK] INT, [LocationID_SK] INT, [DateID_SK] INT, [Sales] FLOAT, [Quantity] INT, [Discount] FLOAT, [Profit] FLOAT, [unit_price] FLOAT);
                PRINT 'Table prod_fact_table created successfully.';
            END
            , parameters: None
[2025-03-28T14:01:19.415+0000] {logging_mixin.py:190} INFO - Table prod_fact_table exists or was just created.
[2025-03-28T14:01:19.427+0000] {logging_mixin.py:190} INFO - Checking and potentially creating table: prod_dim_product
[2025-03-28T14:01:19.452+0000] {sql.py:624} INFO - Running statement: 
            IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'prod_dim_product')
            BEGIN
                CREATE TABLE prod_dim_product ([Product ID] VARCHAR(MAX), [Category] VARCHAR(MAX), [Sub-Category] VARCHAR(MAX), [Product Name] VARCHAR(MAX), [ProductID_SK] INT);
                PRINT 'Table prod_dim_product created successfully.';
            END
            , parameters: None
[2025-03-28T14:01:19.467+0000] {logging_mixin.py:190} INFO - Table prod_dim_product exists or was just created.
[2025-03-28T14:01:19.477+0000] {logging_mixin.py:190} INFO - Checking and potentially creating table: prod_dim_order
[2025-03-28T14:01:19.501+0000] {sql.py:624} INFO - Running statement: 
            IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'prod_dim_order')
            BEGIN
                CREATE TABLE prod_dim_order ([Order ID] VARCHAR(MAX), [Ship Date] VARCHAR(MAX), [Ship Mode] VARCHAR(MAX), [OrderID_SK] INT);
                PRINT 'Table prod_dim_order created successfully.';
            END
            , parameters: None
[2025-03-28T14:01:19.517+0000] {logging_mixin.py:190} INFO - Table prod_dim_order exists or was just created.
[2025-03-28T14:01:19.527+0000] {logging_mixin.py:190} INFO - Checking and potentially creating table: prod_dim_customer
[2025-03-28T14:01:19.551+0000] {sql.py:624} INFO - Running statement: 
            IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'prod_dim_customer')
            BEGIN
                CREATE TABLE prod_dim_customer ([Customer ID] VARCHAR(MAX), [Customer Name] VARCHAR(MAX), [Segment] VARCHAR(MAX), [CustomerID_SK] INT);
                PRINT 'Table prod_dim_customer created successfully.';
            END
            , parameters: None
[2025-03-28T14:01:19.566+0000] {logging_mixin.py:190} INFO - Table prod_dim_customer exists or was just created.
[2025-03-28T14:01:19.574+0000] {logging_mixin.py:190} INFO - Checking and potentially creating table: prod_dim_location
[2025-03-28T14:01:19.598+0000] {sql.py:624} INFO - Running statement: 
            IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'prod_dim_location')
            BEGIN
                CREATE TABLE prod_dim_location ([Postal Code] INT, [City] VARCHAR(MAX), [State] VARCHAR(MAX), [Country] VARCHAR(MAX), [Region] VARCHAR(MAX), [LocationID_SK] INT);
                PRINT 'Table prod_dim_location created successfully.';
            END
            , parameters: None
[2025-03-28T14:01:19.616+0000] {logging_mixin.py:190} INFO - Table prod_dim_location exists or was just created.
[2025-03-28T14:01:19.624+0000] {logging_mixin.py:190} INFO - Checking and potentially creating table: prod_dim_date
[2025-03-28T14:01:19.649+0000] {sql.py:624} INFO - Running statement: 
            IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'prod_dim_date')
            BEGIN
                CREATE TABLE prod_dim_date ([Order Date] VARCHAR(MAX), [DateID_SK] INT, [Order Year] INT, [Order Month] INT, [Order Day] INT);
                PRINT 'Table prod_dim_date created successfully.';
            END
            , parameters: None
[2025-03-28T14:01:19.661+0000] {logging_mixin.py:190} INFO - Table prod_dim_date exists or was just created.
[2025-03-28T14:01:19.669+0000] {logging_mixin.py:190} INFO - Checking and potentially creating table: forecast_past_future_sales
[2025-03-28T14:01:19.697+0000] {sql.py:624} INFO - Running statement: 
            IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'forecast_past_future_sales')
            BEGIN
                CREATE TABLE forecast_past_future_sales ([ds] VARCHAR(MAX), [y] FLOAT, [label] VARCHAR(MAX), [Order Date] FLOAT, [Aggregate Sales] FLOAT);
                PRINT 'Table forecast_past_future_sales created successfully.';
            END
            , parameters: None
[2025-03-28T14:01:19.709+0000] {logging_mixin.py:190} INFO - Table forecast_past_future_sales exists or was just created.
[2025-03-28T14:01:19.717+0000] {logging_mixin.py:190} INFO - Checking and potentially creating table: forecast_metrics
[2025-03-28T14:01:19.737+0000] {sql.py:624} INFO - Running statement: 
            IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'forecast_metrics')
            BEGIN
                CREATE TABLE forecast_metrics ([Metric] VARCHAR(MAX), [Value] FLOAT);
                PRINT 'Table forecast_metrics created successfully.';
            END
            , parameters: None
[2025-03-28T14:01:19.754+0000] {logging_mixin.py:190} INFO - Table forecast_metrics exists or was just created.
[2025-03-28T14:01:19.768+0000] {logging_mixin.py:190} INFO - Truncating table: prod_fact_table
[2025-03-28T14:01:19.789+0000] {sql.py:624} INFO - Running statement: TRUNCATE TABLE prod_fact_table, parameters: None
[2025-03-28T14:01:19.807+0000] {logging_mixin.py:190} INFO - Loading 5000 rows into prod_fact_table
[2025-03-28T14:01:21.546+0000] {sql.py:757} INFO - Loaded 1000 rows into prod_fact_table so far
[2025-03-28T14:01:23.266+0000] {sql.py:757} INFO - Loaded 2000 rows into prod_fact_table so far
[2025-03-28T14:01:25.480+0000] {sql.py:757} INFO - Loaded 3000 rows into prod_fact_table so far
[2025-03-28T14:01:27.519+0000] {sql.py:757} INFO - Loaded 4000 rows into prod_fact_table so far
[2025-03-28T14:01:29.513+0000] {sql.py:757} INFO - Loaded 5000 rows into prod_fact_table so far
[2025-03-28T14:01:29.518+0000] {sql.py:760} INFO - Done loading. Loaded a total of 5000 rows into prod_fact_table
[2025-03-28T14:01:29.537+0000] {logging_mixin.py:190} INFO - Truncating table: prod_dim_product
[2025-03-28T14:01:29.565+0000] {sql.py:624} INFO - Running statement: TRUNCATE TABLE prod_dim_product, parameters: None
[2025-03-28T14:01:29.573+0000] {logging_mixin.py:190} INFO - Loading 1714 rows into prod_dim_product
[2025-03-28T14:01:31.916+0000] {sql.py:757} INFO - Loaded 1000 rows into prod_dim_product so far
[2025-03-28T14:01:33.411+0000] {sql.py:760} INFO - Done loading. Loaded a total of 1714 rows into prod_dim_product
[2025-03-28T14:01:33.428+0000] {logging_mixin.py:190} INFO - Truncating table: prod_dim_order
[2025-03-28T14:01:33.458+0000] {sql.py:624} INFO - Running statement: TRUNCATE TABLE prod_dim_order, parameters: None
[2025-03-28T14:01:33.468+0000] {logging_mixin.py:190} INFO - Loading 2475 rows into prod_dim_order
[2025-03-28T14:01:35.603+0000] {sql.py:757} INFO - Loaded 1000 rows into prod_dim_order so far
[2025-03-28T14:01:37.871+0000] {sql.py:757} INFO - Loaded 2000 rows into prod_dim_order so far
[2025-03-28T14:01:38.585+0000] {sql.py:760} INFO - Done loading. Loaded a total of 2475 rows into prod_dim_order
[2025-03-28T14:01:38.595+0000] {logging_mixin.py:190} INFO - Truncating table: prod_dim_customer
[2025-03-28T14:01:38.618+0000] {sql.py:624} INFO - Running statement: TRUNCATE TABLE prod_dim_customer, parameters: None
[2025-03-28T14:01:38.623+0000] {logging_mixin.py:190} INFO - Loading 756 rows into prod_dim_customer
[2025-03-28T14:01:39.802+0000] {sql.py:760} INFO - Done loading. Loaded a total of 756 rows into prod_dim_customer
[2025-03-28T14:01:39.810+0000] {logging_mixin.py:190} INFO - Truncating table: prod_dim_location
[2025-03-28T14:01:39.831+0000] {sql.py:624} INFO - Running statement: TRUNCATE TABLE prod_dim_location, parameters: None
[2025-03-28T14:01:39.837+0000] {logging_mixin.py:190} INFO - Loading 519 rows into prod_dim_location
[2025-03-28T14:01:40.905+0000] {sql.py:760} INFO - Done loading. Loaded a total of 519 rows into prod_dim_location
[2025-03-28T14:01:40.914+0000] {logging_mixin.py:190} INFO - Truncating table: prod_dim_date
[2025-03-28T14:01:40.937+0000] {sql.py:624} INFO - Running statement: TRUNCATE TABLE prod_dim_date, parameters: None
[2025-03-28T14:01:40.944+0000] {logging_mixin.py:190} INFO - Loading 1012 rows into prod_dim_date
[2025-03-28T14:01:42.586+0000] {sql.py:757} INFO - Loaded 1000 rows into prod_dim_date so far
[2025-03-28T14:01:42.611+0000] {sql.py:760} INFO - Done loading. Loaded a total of 1012 rows into prod_dim_date
[2025-03-28T14:01:42.622+0000] {logging_mixin.py:190} INFO - Truncating table: forecast_past_future_sales
[2025-03-28T14:01:42.645+0000] {sql.py:624} INFO - Running statement: TRUNCATE TABLE forecast_past_future_sales, parameters: None
[2025-03-28T14:01:42.651+0000] {logging_mixin.py:190} INFO - Loading 2389 rows into forecast_past_future_sales
[2025-03-28T14:01:42.687+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 447, in pymssql._pymssql.Cursor.execute
  File "src/pymssql/_mssql.pyx", line 1125, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1156, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1289, in pymssql._mssql.MSSQLConnection.format_and_run_query
  File "src/pymssql/_mssql.pyx", line 1855, in pymssql._mssql.check_cancel_and_raise
  File "src/pymssql/_mssql.pyx", line 1901, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (8114, b'Error converting data type nvarchar to float.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/superstore_dag.py", line 295, in load_data_to_prod_db
    load_csv_to_mssql('forecast_past_future_sales', past_future_sales_file_path, hook)
  File "/opt/airflow/dags/superstore_dag.py", line 273, in load_csv_to_mssql
    hook.insert_rows(table=table_name, rows=df.to_records(index=False), target_fields=df.columns.tolist(),
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 754, in insert_rows
    cur.execute(sql, values)
  File "src/pymssql/_pymssql.pyx", line 465, in pymssql._pymssql.Cursor.execute
pymssql.exceptions.OperationalError: (8114, b'Error converting data type nvarchar to float.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n')
[2025-03-28T14:01:42.706+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-28T14:01:42.708+0000] {logging_mixin.py:190} INFO - Task start:2025-03-28 14:01:18.957149+00:00 end:2025-03-28 14:01:42.705627+00:00 duration:23.748478
[2025-03-28T14:01:42.710+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_data_to_prod_db> dag:<DAG: superstore_dag> dagrun:<DagRun superstore_dag @ 2025-03-28 14:00:55.842262+00:00: manual__2025-03-28T14:00:55.842262+00:00, state:running, queued_at: 2025-03-28 14:00:55.864263+00:00. externally triggered: True>
[2025-03-28T14:01:42.712+0000] {logging_mixin.py:190} INFO - Failure caused by (8114, b'Error converting data type nvarchar to float.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n')
[2025-03-28T14:01:42.713+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=superstore_dag, task_id=load_data_to_prod_db, run_id=manual__2025-03-28T14:00:55.842262+00:00, execution_date=20250328T140055, start_date=20250328T140118, end_date=20250328T140142
[2025-03-28T14:01:42.752+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-28T14:01:42.755+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 73 for task load_data_to_prod_db ((8114, b'Error converting data type nvarchar to float.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n'); 679)
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 447, in pymssql._pymssql.Cursor.execute
  File "src/pymssql/_mssql.pyx", line 1125, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1156, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1289, in pymssql._mssql.MSSQLConnection.format_and_run_query
  File "src/pymssql/_mssql.pyx", line 1855, in pymssql._mssql.check_cancel_and_raise
  File "src/pymssql/_mssql.pyx", line 1901, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (8114, b'Error converting data type nvarchar to float.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/superstore_dag.py", line 295, in load_data_to_prod_db
    load_csv_to_mssql('forecast_past_future_sales', past_future_sales_file_path, hook)
  File "/opt/airflow/dags/superstore_dag.py", line 273, in load_csv_to_mssql
    hook.insert_rows(table=table_name, rows=df.to_records(index=False), target_fields=df.columns.tolist(),
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 754, in insert_rows
    cur.execute(sql, values)
  File "src/pymssql/_pymssql.pyx", line 465, in pymssql._pymssql.Cursor.execute
pymssql.exceptions.OperationalError: (8114, b'Error converting data type nvarchar to float.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n')
[2025-03-28T14:01:42.778+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-28T14:01:42.793+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-28T14:01:42.814+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
