[2025-03-28T13:44:43.413+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-28T13:44:43.430+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superstore_dag.load_data_to_prod_db manual__2025-03-28T13:38:29.844343+00:00 [queued]>
[2025-03-28T13:44:43.442+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superstore_dag.load_data_to_prod_db manual__2025-03-28T13:38:29.844343+00:00 [queued]>
[2025-03-28T13:44:43.445+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-03-28T13:44:43.484+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_data_to_prod_db> on 2025-03-28 13:38:29.844343+00:00
[2025-03-28T13:44:43.493+0000] {standard_task_runner.py:72} INFO - Started process 344 to run task
[2025-03-28T13:44:43.497+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'superstore_dag', 'load_data_to_prod_db', 'manual__2025-03-28T13:38:29.844343+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/superstore_dag.py', '--cfg-path', '/tmp/tmplykje3tp']
[2025-03-28T13:44:43.500+0000] {standard_task_runner.py:105} INFO - Job 67: Subtask load_data_to_prod_db
[2025-03-28T13:44:43.571+0000] {task_command.py:467} INFO - Running <TaskInstance: superstore_dag.load_data_to_prod_db manual__2025-03-28T13:38:29.844343+00:00 [running]> on host b7fc87b83960
[2025-03-28T13:44:43.694+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='superstore_dag' AIRFLOW_CTX_TASK_ID='load_data_to_prod_db' AIRFLOW_CTX_EXECUTION_DATE='2025-03-28T13:38:29.844343+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-28T13:38:29.844343+00:00'
[2025-03-28T13:44:43.697+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-28T13:44:43.699+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-28T13:44:43.702+0000] {logging_mixin.py:190} INFO - Current task name:load_data_to_prod_db state:running start_date:2025-03-28 13:44:43.432831+00:00
[2025-03-28T13:44:43.704+0000] {logging_mixin.py:190} INFO - Dag name:superstore_dag and current dag run status:running
[2025-03-28T13:44:43.706+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-28T13:44:43.731+0000] {logging_mixin.py:190} INFO - Checking and potentially creating table: prod_fact_table
[2025-03-28T13:44:43.743+0000] {base.py:84} INFO - Retrieving connection '***_default'
[2025-03-28T13:44:43.780+0000] {sql.py:624} INFO - Running statement: 
            IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'prod_fact_table')
            BEGIN
                CREATE TABLE prod_fact_table ([OrderID_SK] INT, [ProductID_SK] INT, [CustomerID_SK] INT, [LocationID_SK] INT, [DateID_SK] INT, [Sales] FLOAT, [Quantity] INT, [Discount] FLOAT, [Profit] FLOAT, [unit_price] FLOAT);
                PRINT 'Table prod_fact_table created successfully.';
            END
            , parameters: None
[2025-03-28T13:44:43.805+0000] {logging_mixin.py:190} INFO - Table prod_fact_table exists or was just created.
[2025-03-28T13:44:43.829+0000] {logging_mixin.py:190} INFO - Checking and potentially creating table: prod_dim_product
[2025-03-28T13:44:43.860+0000] {sql.py:624} INFO - Running statement: 
            IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'prod_dim_product')
            BEGIN
                CREATE TABLE prod_dim_product ([Product ID] VARCHAR(MAX), [Category] VARCHAR(MAX), [Sub-Category] VARCHAR(MAX), [Product Name] VARCHAR(MAX), [ProductID_SK] INT);
                PRINT 'Table prod_dim_product created successfully.';
            END
            , parameters: None
[2025-03-28T13:44:43.875+0000] {logging_mixin.py:190} INFO - Table prod_dim_product exists or was just created.
[2025-03-28T13:44:43.892+0000] {logging_mixin.py:190} INFO - Checking and potentially creating table: prod_dim_order
[2025-03-28T13:44:43.922+0000] {sql.py:624} INFO - Running statement: 
            IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'prod_dim_order')
            BEGIN
                CREATE TABLE prod_dim_order ([Order ID] VARCHAR(MAX), [Ship Date] VARCHAR(MAX), [Ship Mode] VARCHAR(MAX), [OrderID_SK] INT);
                PRINT 'Table prod_dim_order created successfully.';
            END
            , parameters: None
[2025-03-28T13:44:43.935+0000] {logging_mixin.py:190} INFO - Table prod_dim_order exists or was just created.
[2025-03-28T13:44:43.947+0000] {logging_mixin.py:190} INFO - Checking and potentially creating table: prod_dim_customer
[2025-03-28T13:44:43.977+0000] {sql.py:624} INFO - Running statement: 
            IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'prod_dim_customer')
            BEGIN
                CREATE TABLE prod_dim_customer ([Customer ID] VARCHAR(MAX), [Customer Name] VARCHAR(MAX), [Segment] VARCHAR(MAX), [CustomerID_SK] INT);
                PRINT 'Table prod_dim_customer created successfully.';
            END
            , parameters: None
[2025-03-28T13:44:43.991+0000] {logging_mixin.py:190} INFO - Table prod_dim_customer exists or was just created.
[2025-03-28T13:44:44.007+0000] {logging_mixin.py:190} INFO - Checking and potentially creating table: prod_dim_location
[2025-03-28T13:44:44.035+0000] {sql.py:624} INFO - Running statement: 
            IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'prod_dim_location')
            BEGIN
                CREATE TABLE prod_dim_location ([Postal Code] INT, [City] VARCHAR(MAX), [State] VARCHAR(MAX), [Country] VARCHAR(MAX), [Region] VARCHAR(MAX), [LocationID_SK] INT);
                PRINT 'Table prod_dim_location created successfully.';
            END
            , parameters: None
[2025-03-28T13:44:44.048+0000] {logging_mixin.py:190} INFO - Table prod_dim_location exists or was just created.
[2025-03-28T13:44:44.060+0000] {logging_mixin.py:190} INFO - Checking and potentially creating table: prod_dim_date
[2025-03-28T13:44:44.088+0000] {sql.py:624} INFO - Running statement: 
            IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'prod_dim_date')
            BEGIN
                CREATE TABLE prod_dim_date ([Order Date] VARCHAR(MAX), [DateID_SK] INT, [Order Year] INT, [Order Month] INT, [Order Day] INT);
                PRINT 'Table prod_dim_date created successfully.';
            END
            , parameters: None
[2025-03-28T13:44:44.104+0000] {logging_mixin.py:190} INFO - Table prod_dim_date exists or was just created.
[2025-03-28T13:44:44.131+0000] {logging_mixin.py:190} INFO - Truncating table: prod_fact_table
[2025-03-28T13:44:44.159+0000] {sql.py:624} INFO - Running statement: TRUNCATE TABLE prod_fact_table, parameters: None
[2025-03-28T13:44:44.168+0000] {logging_mixin.py:190} INFO - Loading 9994 rows into prod_fact_table
[2025-03-28T13:44:46.573+0000] {sql.py:757} INFO - Loaded 1000 rows into prod_fact_table so far
[2025-03-28T13:44:48.719+0000] {sql.py:757} INFO - Loaded 2000 rows into prod_fact_table so far
[2025-03-28T13:44:51.036+0000] {sql.py:757} INFO - Loaded 3000 rows into prod_fact_table so far
[2025-03-28T13:44:53.566+0000] {sql.py:757} INFO - Loaded 4000 rows into prod_fact_table so far
[2025-03-28T13:44:55.664+0000] {sql.py:757} INFO - Loaded 5000 rows into prod_fact_table so far
[2025-03-28T13:44:57.810+0000] {sql.py:757} INFO - Loaded 6000 rows into prod_fact_table so far
[2025-03-28T13:44:59.689+0000] {sql.py:757} INFO - Loaded 7000 rows into prod_fact_table so far
[2025-03-28T13:45:01.505+0000] {sql.py:757} INFO - Loaded 8000 rows into prod_fact_table so far
[2025-03-28T13:45:03.942+0000] {sql.py:757} INFO - Loaded 9000 rows into prod_fact_table so far
[2025-03-28T13:45:06.067+0000] {sql.py:760} INFO - Done loading. Loaded a total of 9994 rows into prod_fact_table
[2025-03-28T13:45:06.078+0000] {logging_mixin.py:190} INFO - Truncating table: prod_dim_product
[2025-03-28T13:45:06.100+0000] {sql.py:624} INFO - Running statement: TRUNCATE TABLE prod_dim_product, parameters: None
[2025-03-28T13:45:06.107+0000] {logging_mixin.py:190} INFO - Loading 1862 rows into prod_dim_product
[2025-03-28T13:45:07.966+0000] {sql.py:757} INFO - Loaded 1000 rows into prod_dim_product so far
[2025-03-28T13:45:09.906+0000] {sql.py:760} INFO - Done loading. Loaded a total of 1862 rows into prod_dim_product
[2025-03-28T13:45:09.929+0000] {logging_mixin.py:190} INFO - Truncating table: prod_dim_order
[2025-03-28T13:45:09.960+0000] {sql.py:624} INFO - Running statement: TRUNCATE TABLE prod_dim_order, parameters: None
[2025-03-28T13:45:09.970+0000] {logging_mixin.py:190} INFO - Loading 5009 rows into prod_dim_order
[2025-03-28T13:45:12.010+0000] {sql.py:757} INFO - Loaded 1000 rows into prod_dim_order so far
[2025-03-28T13:45:14.441+0000] {sql.py:757} INFO - Loaded 2000 rows into prod_dim_order so far
[2025-03-28T13:45:16.295+0000] {sql.py:757} INFO - Loaded 3000 rows into prod_dim_order so far
[2025-03-28T13:45:18.413+0000] {sql.py:757} INFO - Loaded 4000 rows into prod_dim_order so far
[2025-03-28T13:45:20.682+0000] {sql.py:757} INFO - Loaded 5000 rows into prod_dim_order so far
[2025-03-28T13:45:20.706+0000] {sql.py:760} INFO - Done loading. Loaded a total of 5009 rows into prod_dim_order
[2025-03-28T13:45:20.721+0000] {logging_mixin.py:190} INFO - Truncating table: prod_dim_customer
[2025-03-28T13:45:20.748+0000] {sql.py:624} INFO - Running statement: TRUNCATE TABLE prod_dim_customer, parameters: None
[2025-03-28T13:45:20.760+0000] {logging_mixin.py:190} INFO - Loading 793 rows into prod_dim_customer
[2025-03-28T13:45:21.999+0000] {sql.py:760} INFO - Done loading. Loaded a total of 793 rows into prod_dim_customer
[2025-03-28T13:45:22.011+0000] {logging_mixin.py:190} INFO - Truncating table: prod_dim_location
[2025-03-28T13:45:22.033+0000] {sql.py:624} INFO - Running statement: TRUNCATE TABLE prod_dim_location, parameters: None
[2025-03-28T13:45:22.041+0000] {logging_mixin.py:190} INFO - Loading 631 rows into prod_dim_location
[2025-03-28T13:45:23.461+0000] {sql.py:760} INFO - Done loading. Loaded a total of 631 rows into prod_dim_location
[2025-03-28T13:45:23.474+0000] {logging_mixin.py:190} INFO - Truncating table: prod_dim_date
[2025-03-28T13:45:23.503+0000] {sql.py:624} INFO - Running statement: TRUNCATE TABLE prod_dim_date, parameters: None
[2025-03-28T13:45:23.515+0000] {logging_mixin.py:190} INFO - Loading 1237 rows into prod_dim_date
[2025-03-28T13:45:25.401+0000] {sql.py:757} INFO - Loaded 1000 rows into prod_dim_date so far
[2025-03-28T13:45:25.748+0000] {sql.py:760} INFO - Done loading. Loaded a total of 1237 rows into prod_dim_date
[2025-03-28T13:45:25.778+0000] {logging_mixin.py:190} INFO - Checking and potentially creating table: forecast_past_future_sales
[2025-03-28T13:45:25.786+0000] {logging_mixin.py:190} INFO - Error creating table forecast_past_future_sales: The conn_id `***_prod2` isn't defined
[2025-03-28T13:45:25.798+0000] {logging_mixin.py:190} INFO - Checking and potentially creating table: forecast_metrics
[2025-03-28T13:45:25.807+0000] {logging_mixin.py:190} INFO - Error creating table forecast_metrics: The conn_id `***_prod2` isn't defined
[2025-03-28T13:45:25.822+0000] {logging_mixin.py:190} INFO - Truncating table: forecast_past_future_sales
[2025-03-28T13:45:25.844+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/superstore_dag.py", line 305, in load_data_to_prod_db
    load_csv_to_mssql('forecast_past_future_sales', past_future_sales_file_path, forecast_hook)
  File "/opt/airflow/dags/superstore_dag.py", line 281, in load_csv_to_mssql
    hook.run(f"TRUNCATE TABLE {table_name}")
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 576, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 684, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/microsoft/mssql/hooks/mssql.py", line 101, in get_conn
    conn = self.connection
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 242, in connection
    self._connection = self.get_connection(self.get_conn_id())
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `***_prod2` isn't defined
[2025-03-28T13:45:25.855+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-28T13:45:25.857+0000] {logging_mixin.py:190} INFO - Task start:2025-03-28 13:44:43.432831+00:00 end:2025-03-28 13:45:25.855396+00:00 duration:42.422565
[2025-03-28T13:45:25.860+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_data_to_prod_db> dag:<DAG: superstore_dag> dagrun:<DagRun superstore_dag @ 2025-03-28 13:38:29.844343+00:00: manual__2025-03-28T13:38:29.844343+00:00, state:running, queued_at: 2025-03-28 13:38:29.874927+00:00. externally triggered: True>
[2025-03-28T13:45:25.862+0000] {logging_mixin.py:190} INFO - Failure caused by The conn_id `***_prod2` isn't defined
[2025-03-28T13:45:25.864+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=superstore_dag, task_id=load_data_to_prod_db, run_id=manual__2025-03-28T13:38:29.844343+00:00, execution_date=20250328T133829, start_date=20250328T134443, end_date=20250328T134525
[2025-03-28T13:45:25.899+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-28T13:45:25.901+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 67 for task load_data_to_prod_db (The conn_id `***_prod2` isn't defined; 344)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/superstore_dag.py", line 305, in load_data_to_prod_db
    load_csv_to_mssql('forecast_past_future_sales', past_future_sales_file_path, forecast_hook)
  File "/opt/airflow/dags/superstore_dag.py", line 281, in load_csv_to_mssql
    hook.run(f"TRUNCATE TABLE {table_name}")
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 576, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 684, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/microsoft/mssql/hooks/mssql.py", line 101, in get_conn
    conn = self.connection
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 242, in connection
    self._connection = self.get_connection(self.get_conn_id())
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `***_prod2` isn't defined
[2025-03-28T13:45:25.942+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-28T13:45:25.973+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-28T13:45:25.998+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
